config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # the default route
  root 'landing#index'

  # login & protected page
  get 'login' => 'sessions#index'
  get 'profile' => 'profile#index'
  get 'dashboard' => 'dashboard#index'

  # static pages have to be explicitly be mentioned due to the catch-all rule below
  get 'pages/about' => 'high_voltage/pages#show', id: 'about'
  get 'pages/help' => 'high_voltage/pages#show', id: 'help'
  get 'pages/imprint' => 'high_voltage/pages#show', id: 'imprint'
  get 'pages/privacy' => 'high_voltage/pages#show', id: 'privacy'

  # OAuth etc
  get 'auth/github/callback', to: 'sessions#create_github'
  get 'auth/discord/callback', to: 'sessions#create_discord'
  get 'auth/google_oauth2/callback', to: 'sessions#create_google'
  get '/logout', to: 'sessions#logout'

  # catch all
  match '*unmatched', to: 'errors#page_not_found', via: :all
end

app/models/authentication.rb
# frozen_string_literal: true

class Authentication
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :client_id, :string
  attribute :client_secret, :string
  attribute :expires, :integer
  attribute :roles, :string

  def set_defaults
    @expires = 0
    # permitted[:repetition_penalty] = 1.15
    # permitted[:num_beams] = 1
    # permitted[:do_sample] = false
    # permitted[:top_p] = 1.0
    # permitted[:top_k] = 50
    # permitted[:skip_prompt] = true
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController provides generic behaviour
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Error::ErrorHandler

  # enforce parameters
  ActionController::Parameters.action_on_unpermitted_parameters = :raise

  def authenticate_account!
    redirect_to login_path unless account_signed_in?
  end

  def account_signed_in?
    return true unless session[:user_id].nil?

    false
  end

  rescue_from ActionController::UnknownFormat, ActionView::MissingTemplate do
    respond_to_error(:not_found, 500, 'not found')
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# Stuff shown after login
class DashboardController < ApplicationController
  before_action :authenticate_account!

  def index; end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

# Gracefully handle errors
class ErrorsController < ApplicationController
  protect_from_forgery with: :null_session
  include Error::ErrorHandler

  def page_not_found
    respond_to_error(:page_not_found, 404, 'not found')
  end
end

app/controllers/landing_controller.rb
# frozen_string_literal: true

# Stuff shown to anoymous users
class LandingController < ApplicationController
  # before_action :authenticate_account!

  def index
    redirect_to '/dashboard' if account_signed_in?
  end
end

app/controllers/profile_controller.rb
# frozen_string_literal: true

# The user's settings etc
class ProfileController < ApplicationController
  before_action :authenticate_account!

  def index; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# SessionsController handles sign-in & sign-out etc.
class SessionsController < ApplicationController
  def index; end

  def create_github
    auth_hash = request.env['omniauth.auth']
    email = auth_hash.info['email']
    uid = auth_hash.uid

    auth = authentciate_client email
    redirect_to root_path if auth.nil?

    create_session uid, email, auth['client_secret'], 'github'

    redirect_to dashboard_path
  end

  def create_google2
    auth_hash = request.env['omniauth.auth']
    email = auth_hash.info['email']
    uid = auth_hash.uid

    auth = authentciate_client email
    redirect_to root_path if auth.nil?

    create_session uid, email, auth['client_secret'], 'google'

    redirect_to dashboard_path
  end

  def create_google
    auth_hash = request.env['omniauth.auth']
    authenticate_client auth_hash, 'google'
  end

  def create_discord
    auth_hash = request.env['omniauth.auth']
    email = auth_hash.info['email']
    uid = auth_hash.uid

    auth = authentciate_client email
    redirect_to root_path if auth.nil?

    create_session uid, email, auth['client_secret'], 'discord'

    redirect_to dashboard_path
  end

  def logout
    AuthenticationService.revoke_client session[:user_email] # FIXME: check response?
    # delete the session anyways ...
    session[:user_id] = nil
    session[:user_email] = nil
    session[:provider] = nil
    session[:client_secret] = nil

    redirect_to root_path
  end

  private

  def authenticate_client(auth_hash, provider)
    email = auth_hash.info['email']
    uid = auth_hash.uid

    auth = register_client email
    redirect_to root_path if auth.nil?

    create_session uid, email, auth['client_secret'], provider

    redirect_to dashboard_path
  end

  def register_client(email)
    auth = Authentication.new
    auth.client_id = "#{ENV.fetch('PROJECT_ID', 'default')}.#{email}"

    AuthenticationService.register_client auth
  end

  def create_session(uid, email, secret, provider)
    session[:user_id] = uid
    session[:user_email] = email
    session[:client_secret] = secret
    session[:provider] = provider
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Some basic helper functions
module ApplicationHelper
  APP_NAME = 'minimal-rails'

  def formatted_title(title = nil)
    return APP_NAME if title.nil?

    "#{APP_NAME} - #{title}"
  end

  def signed_in?
    return true unless session[:user_id].nil?

    false
  end

  def oauth_provider
    session[:provider]
  end

  def current_user_id
    session[:user_id]
  end

  def current_user_email
    session[:user_email]
  end
end

app/views/dashboard/index.html.erb
<% content_for :page_title, formatted_title('Dashboard') %>

<div class='container mx-auto max-w-7xl px-2 py-2'>
    <h1 class='text-3xl font-bold underline'>Dashboard</h1>        
</div>

app/views/landing/index.html.erb
<% content_for :page_title, formatted_title('Home') %>

<div class='container mx-auto max-w-7xl px-2 py-2'>
    <h1 class='text-3xl font-bold underline'>Landing Page</h1>        
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  
  <head>
    <title><%= yield :page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body class='h-full'>
    <%= render 'shared/nav' %>
  
    <main class=''>
      <%= yield %>
    </main>
  
    <div class='bg-neutral border-t-2 border-t-light'>
      <%= render 'shared/footer' %>
    </div>

  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html class="h-full">
  
  <head>
    <title><%= yield :page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body class='h-full'>
    <%= render 'shared/nav' %>
  
    <main class=''>
      <div class='container mx-auto max-w-7xl px-2 py-2'>
        <%= yield %>
      </div>
    </main>
  
    <div class='bg-custom1 '>
      <%= render 'shared/footer' %>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<% content_for :page_title, formatted_title('about') %>

<h1 class='text-3xl font-bold underline'>About</h1>

<p>About this app goes here ...</p>

app/views/pages/help.html.erb
<% content_for :page_title, formatted_title('help') %>

<h1 class='text-3xl font-bold underline'>Help</h1>

<p>Help for this app goes here ...</p>

app/views/pages/imprint.html.erb
<% content_for :page_title, formatted_title('impressum / imprint') %>

<h1 class='text-3xl font-bold underline'>Impressum/Imprint</h1>

<p>Legal foo goes here ...</p>

app/views/pages/privacy.html.erb
<% content_for :page_title, formatted_title('privacy') %>

<h1 class='text-3xl font-bold underline'>Data Privacy</h1>

<p>It is very simple:</p>
<p>We collect only essential data needed for our operations. We do not sell or share this data with others.</p>
<p>That's all.</p>

app/views/shared/_footer.html.erb
<footer class='mx-auto max-w-7xl px-2 body-font'>
    
    <div class='flex flex-row py-2 space-x-4'>
        <div><%= link_to 'About', page_path('about'), class: '' %></div>
        <div><%= link_to 'Impressum / Imprint', page_path('imprint'), class: '' %></div>
        <div><%= link_to 'Data Privacy', page_path('privacy'), class: '' %></div>
    </div>
    
    <div class='container px-1 py-1 mx-auto flex items-center sm:flex-row flex-col'>        
        <%= link_to root_path, class: 'flex title-font font-medium items-center md:justify-start justify-center' do %>
            <%= image_tag('logo1x1.png') %>
            <span class='ml-3 text-xl'>COMPANY</span>
        <% end %>

        <p class='text-sm ml-2 pl-2 md:border-l'>
            © 2023 COMPANY —
            <a href="https://mastodon.social/" class='text-gray-600 ml-1' rel='noopener noreferrer' target='_blank'>@company</a>
        </p>
        
        <nav class='inline-flex justify-center sm:ml-auto sm:justify-start'>
            <a href='#' class='mr-5'>Link</a>
            <a href='#' class='mr-5'>Link</a>
            <a href='#' class='mr-5'>Link</a>
            <a href='#' class='mr-5'>Link</a>
        </nav>
    </div>

    <% if signed_in? %>
        <%= session.id %> [<%= current_user_id %>/<%= current_user_email %> on <%= oauth_provider %>]
    <% end %>
</footer>

app/views/shared/_nav.html.erb
<header class='text-gray-600 body-font border-b-2 border-b-light'>
    <div class='container mx-auto max-w-7xl flex flex-wrap p-2 flex-col md:flex-row items-center'>
        
        <%= link_to root_path, class: 'flex title-font font-medium items-center md:justify-start justify-center text-gray-900' do %>
            <%= image_tag('logo1x1.png') %>
            <span class='ml-3 text-xl'>COMPANY</span>
        <% end %>
        
        <nav class='md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l flex flex-wrap items-center text-base justify-center'>
            <a href='#' class='mr-5'>Link</a>
            <a href='#' class='mr-5'>Link</a>
            <a href='#' class='mr-5'>Link</a>
            <a href='#' class='mr-5'>Link</a>
        </nav>

        <div class='space-x-2 lg:justify-end'>
            <% if signed_in? %>
                <%= link_to 'Profile', profile_path, class: 'text-sm leading-6 text-gray-900' %>
                <%= link_to 'Sign Out', logout_path, class: 'text-sm leading-6 text-gray-900' %>
            <% else %>
                <%= link_to 'Log In', login_path, class: 'text-sm leading-6 text-gray-900' %>
            <% end %>
        
        </div>

    </div>
</header>